# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/one',
                'doc_host': 'https://jbwhit.github.io',
                'git_url': 'https://github.com/jbwhit/one',
                'lib_path': 'one'},
  'syms': {'one.core': {'one.core.foo': ('core.html#foo', 'one/core.py')}}}
